/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as PencakSilatRouteImport } from './routes/pencak-silat'
import { Route as DisciplinesIndexRouteImport } from './routes/disciplines.index'
import { Route as DisciplinesGandaRouteImport } from './routes/disciplines.ganda'
import { Route as DisciplinesTandingRouteImport } from './routes/disciplines.tanding'
import { Route as DisciplinesTunggalRouteImport } from './routes/disciplines.tunggal'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const PencakSilatRoute = PencakSilatRouteImport.update({
  id: '/pencak-silat',
  path: '/pencak-silat',
  getParentRoute: () => rootRouteImport,
} as any)
const DisciplinesIndexRoute = DisciplinesIndexRouteImport.update({
  id: '/disciplines/',
  path: '/disciplines/',
  getParentRoute: () => rootRouteImport,
} as any)
const DisciplinesGandaRoute = DisciplinesGandaRouteImport.update({
  id: '/disciplines/ganda',
  path: '/disciplines/ganda',
  getParentRoute: () => rootRouteImport,
} as any)
const DisciplinesTandingRoute = DisciplinesTandingRouteImport.update({
  id: '/disciplines/tanding',
  path: '/disciplines/tanding',
  getParentRoute: () => rootRouteImport,
} as any)
const DisciplinesTunggalRoute = DisciplinesTunggalRouteImport.update({
  id: '/disciplines/tunggal',
  path: '/disciplines/tunggal',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/pencak-silat': typeof PencakSilatRoute
  '/disciplines/ganda': typeof DisciplinesGandaRoute
  '/disciplines/tanding': typeof DisciplinesTandingRoute
  '/disciplines/tunggal': typeof DisciplinesTunggalRoute
  '/disciplines/': typeof DisciplinesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/pencak-silat': typeof PencakSilatRoute
  '/disciplines/ganda': typeof DisciplinesGandaRoute
  '/disciplines/tanding': typeof DisciplinesTandingRoute
  '/disciplines/tunggal': typeof DisciplinesTunggalRoute
  '/disciplines': typeof DisciplinesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/pencak-silat': typeof PencakSilatRoute
  '/disciplines/ganda': typeof DisciplinesGandaRoute
  '/disciplines/tanding': typeof DisciplinesTandingRoute
  '/disciplines/tunggal': typeof DisciplinesTunggalRoute
  '/disciplines/': typeof DisciplinesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/pencak-silat'
    | '/disciplines/ganda'
    | '/disciplines/tanding'
    | '/disciplines/tunggal'
    | '/disciplines/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/pencak-silat'
    | '/disciplines/ganda'
    | '/disciplines/tanding'
    | '/disciplines/tunggal'
    | '/disciplines'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/pencak-silat'
    | '/disciplines/ganda'
    | '/disciplines/tanding'
    | '/disciplines/tunggal'
    | '/disciplines/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PencakSilatRoute: typeof PencakSilatRoute
  DisciplinesGandaRoute: typeof DisciplinesGandaRoute
  DisciplinesTandingRoute: typeof DisciplinesTandingRoute
  DisciplinesTunggalRoute: typeof DisciplinesTunggalRoute
  DisciplinesIndexRoute: typeof DisciplinesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pencak-silat': {
      id: '/pencak-silat'
      path: '/pencak-silat'
      fullPath: '/pencak-silat'
      preLoaderRoute: typeof PencakSilatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disciplines/': {
      id: '/disciplines/'
      path: '/disciplines'
      fullPath: '/disciplines/'
      preLoaderRoute: typeof DisciplinesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disciplines/ganda': {
      id: '/disciplines/ganda'
      path: '/disciplines/ganda'
      fullPath: '/disciplines/ganda'
      preLoaderRoute: typeof DisciplinesGandaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disciplines/tanding': {
      id: '/disciplines/tanding'
      path: '/disciplines/tanding'
      fullPath: '/disciplines/tanding'
      preLoaderRoute: typeof DisciplinesTandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disciplines/tunggal': {
      id: '/disciplines/tunggal'
      path: '/disciplines/tunggal'
      fullPath: '/disciplines/tunggal'
      preLoaderRoute: typeof DisciplinesTunggalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PencakSilatRoute: PencakSilatRoute,
  DisciplinesGandaRoute: DisciplinesGandaRoute,
  DisciplinesTandingRoute: DisciplinesTandingRoute,
  DisciplinesTunggalRoute: DisciplinesTunggalRoute,
  DisciplinesIndexRoute: DisciplinesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
